### PR TITLE
add username and password command line arguments

### PR DESCRIPTION
**Pull request by torypages**
This makes writing a one line ftp server more flexible.

### CODE REVIEW

**Comment by giampaolo** [comment]
Looks good. Just update HISTORY a CREDITS files

**Comment by torypages** [comment]
I believe I have made the required changes, force pushed, and I think things should be ready to go! Thanks a bunch! Provided that everything is good to go it will my first commit to a public project! Thanks for being friendly!

**Comment by giampaolo** [comment]
Sorry for the astonishing delay in responding to this. If you're still interested, just resolve conflicts of this PR and I'll merge it.

**Comment by giampaolo** [comment]
Merged as https://github.com/giampaolo/pyftpdlib/commit/9947ee9e3f2ad38a59d1c6755f8ec0c7c5d14a2c

**Pull request merged**
